{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "143384b8_6316ff6b",
        "filename": "include/sdbusplus/asio/object_server.hpp",
        "patchSetId": 1
      },
      "lineNbr": 201,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2022-08-19T13:29:19Z",
      "side": 1,
      "message": "This is probably fine for now.  I did some refactoring not too long ago so that `sdbusplus::exception_t` now has `get_errno()`.  I should fix up the new_method_error function so that it adds the errno to the message now as well.  Then we can make this all one common path.",
      "range": {
        "startLine": 193,
        "startChar": 0,
        "endLine": 201,
        "endChar": 17
      },
      "revId": "91e0135a71583018201570fbefcbcf67d8056421",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}